## Custom errors, extending Error

we can extend the default ``Error`` class to provide extra details about the error occuring. 
Our errors should support basic error properties like message, name and, preferably, stack. But they also may have other properties of their own, e.g. ``HttpError`` objects may have a ``statusCode`` property with a value like ``404`` or ``403`` or ``500``.

### Extending Error: 
A normal and valid json would look like 
```js
let json = `{ "name": "John", "age": 30 }`;
```

It may be valid json but if it's missing some fields we may throw an error. We will have a function which will not only throw ``SyntaxError`` on  invalid json object but also validation error if we will have any missing fields. 

```js
class ValidationError extends Error {
    constructor(message){
        super(message) // calls parent Error class which sets this message property
        this.name = 'ValidationError' // we set the name manually.
    }
}
function readUser(jsonData){
    let user = JSON.parse(jsonData) // throws syntax error for malformed json

    if(!jsonData.name){
        throw new ValidationError('No Name found')
    }
    if(!jsonData.age){
        throw new ValidationError('No Age found')
    }

    return user;
}

try{
    let user = readUser('{ "age": 25 }');
}
catch(err){
    if (err instanceof ValidationError) {
    alert("Invalid data: " + err.message); // Invalid data: No field: name
  } else if (err instanceof SyntaxError) { // (*)
    alert("JSON Syntax Error: " + err.message);
  } else {
    throw err; // unknown error, rethrow it (**)
  }
}
```
We call the parent constructor. JavaScript requires us to call super in the child constructor, so that’s obligatory. The parent constructor sets the message property.

The parent constructor also sets the name property to "Error", so in the line (2) we reset it to the right value.

The ``try..catch`` block in the code above handles both our ``ValidationError`` and the built-in ``SyntaxError`` from ``JSON.parse``.

The ``instanceof`` version is much better, because in the future we are going to extend ``ValidationError``, make subtypes of it, like ``PropertyRequiredError``. And ``instanceof`` check will continue to work for new inheriting classes. So that’s future-proof.

Also it’s important that if catch meets an unknown error, then it rethrows it in the line (**).

### Further Inheritance 
```js
class ValidationError extends Error {
    constructor(message){
        super(message) // calls parent Error class which sets this message property
        this.name = 'ValidationError' // we set the name manually.
    }
}

class PropertyRequiredError extends ValidationError {
    constructor(property){
        super('No Property' + property)
        this.name = 'PropertyRequiredError'
        this.property = property
    }
}
function readUser(jsonData){
    let user = JSON.parse(jsonData) // throws syntax error for malformed json

    if(!jsonData.name){
        throw new PropertyRequiredError('name')
    }
    if(!jsonData.age){
        throw new ValidationError('Age')
    }

    return user;
}

try{
    let user = readUser('{ "age": 25 }');
}
catch(err){
    if (err instanceof ValidationError) {
    alert("Invalid data: " + err.message); // Invalid data: No field: name
  } else if (err instanceof SyntaxError) { // (*)
    alert("JSON Syntax Error: " + err.message);
  } else {
    throw err; // unknown error, rethrow it (**)
  }
}
```

## Wrapping Exceptions
The purpose of the function ``readUser`` in the code above is “to read the user data”. There may occur different kinds of errors in the process. Right now we have ``SyntaxError`` and ``ValidationError``, but in the future ``readUser`` function may grow and probably generate other kinds of errors.

The code which calls ``readUser`` should handle these errors. Right now it uses multiple ``ifs`` in the catch block, that check the class and handle known errors and rethrow the unknown ones.

Multiple if blocks can lead to unwanted code blocks. 
We just want to know if there was a “data reading error” – why exactly it happened is often irrelevant (the error message describes it). Or, even better, we’d like to have a way to get the error details, but only if we need to.

The technique that we describe here is called “wrapping exceptions”.

- We’ll make a new class ``ReadError`` to represent a generic “data reading” error.
- The function ``readUser`` will catch data reading errors that occur inside it, such as ``ValidationError`` and ``SyntaxError``, and generate a ``ReadError`` instead.
- The ReadError object will keep the reference to the original error in its cause property.

Then the code that calls readUser will only have to check for ``ReadError``, not for every kind of data reading errors. And if it needs more details of an error, it can check its cause property.

```js
class ReadError extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = 'ReadError';
  }
}

class ValidationError extends Error { /*...*/ }
class PropertyRequiredError extends ValidationError { /* ... */ }

function validateUser(user) {
  if (!user.age) {
    throw new PropertyRequiredError("age");
  }

  if (!user.name) {
    throw new PropertyRequiredError("name");
  }
}

function readUser(json) {
  let user;

  try {
    user = JSON.parse(json);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new ReadError("Syntax Error", err);
    } else {
      throw err;
    }
  }

  try {
    validateUser(user);
  } catch (err) {
    if (err instanceof ValidationError) {
      throw new ReadError("Validation Error", err);
    } else {
      throw err;
    }
  }

}

try {
  readUser('{bad json}');
} catch (e) {
  if (e instanceof ReadError) {
    alert(e);
    // Original error: SyntaxError: Unexpected token b in JSON at position 1
    alert("Original error: " + e.cause);
  } else {
    throw e;
  }
}
```